import { Inter } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  console.log(params.locale);
  return (
    <html lang={params.locale}>
      <body className="font-primary h-[3000px]">{children}</body>
    </html>
  );
}
