import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  return (
    <html lang={params.locale}>
      <body className="font-primary">{children}</body>
    </html>
  );
}
